<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'notificacao' => '/Notificacao.inc.php',
                'tradutorpluginnotificacao' => '/TradutorPluginNotificacao.inc.php',
                'tradutortestes' => '/TradutorTestes.inc.php',
                'tradutorpkp' => '/TradutorPKP.inc.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
