<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'notificacaoatualizacaoplugin' => '/NotificacaoAtualizacaoPlugin.inc.php',
                'tradutornotificacao' => '/TradutorNotificacao.inc.php',
                'tradutornotificacaotestes' => '/TradutorNotificacaoTestes.inc.php',
                'tradutornotificacaopkp' => '/TradutorNotificacaoPKP.inc.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
